"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Category, commandHeaders, Product, ProductMedia, Variant } from "../../api";
import { catalogSlug } from "../../catalog-slug";
import styles from "../../admin.module.css";

type Form = { name:string; slug:string; shortDescription:string; description:string; price:string; primaryCategoryId:string };
type MerchandisingForm = { newArrival:boolean; newUntil:string; onSale:boolean; salePercent:string };
type Upload = { objectKey:string; uploadUrl:string; contentType:string };
const empty:Form = { name:"", slug:"", shortDescription:"", description:"", price:"", primaryCategoryId:"" };
const emptyMerchandising:MerchandisingForm = { newArrival:false, newUntil:"", onSale:false, salePercent:"" };
const statusLabel={DRAFT:"Черновик",ACTIVE:"Опубликован",ARCHIVED:"В архиве"} as const;

export default function ProductEditor({ id }: { id?:string }) {
  const [form,setForm]=useState<Form>(empty), [categories,setCategories]=useState<Category[]>([]), [variants,setVariants]=useState<Variant[]>([]), [media,setMedia]=useState<ProductMedia[]>([]);
  const [merchandising,setMerchandising]=useState<MerchandisingForm>(emptyMerchandising);
  const [etag,setEtag]=useState<string|null>(null), [status,setStatus]=useState<Product["status"]>("DRAFT");
  const [error,setError]=useState(""), [message,setMessage]=useState(""), [busy,setBusy]=useState(false);
  const [label,setLabel]=useState(""), [file,setFile]=useState<File|null>(null);
  const [uploadProgress,setUploadProgress]=useState<number|null>(null), [uploadPhase,setUploadPhase]=useState("");
  const [previewUrl,setPreviewUrl]=useState(""), [draggingFile,setDraggingFile]=useState(false);
  const update=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  const updateMerchandising=(patch:Partial<MerchandisingForm>)=>setMerchandising(current=>({...current,...patch}));
  const loadProduct=async()=>{if(!id)return;const response=await api<Product>(`/admin/catalog/products/${id}`);setForm({name:response.data.name,slug:response.data.slug,shortDescription:response.data.shortDescription,description:response.data.description,price:response.data.priceMinor?String(response.data.priceMinor/100):"",primaryCategoryId:response.data.primaryCategoryId});const promo=response.data.merchandising;setMerchandising({newArrival:promo?.newArrival??false,newUntil:promo?.newUntil?toLocalDateTime(promo.newUntil):"",onSale:promo?.onSale??false,salePercent:promo?.salePercent?String(promo.salePercent):""});setStatus(response.data.status);setVariants(response.data.variants??[]);setMedia(response.data.media??[]);setEtag(response.etag)};
  useEffect(()=>{void api<{items:Category[]}>('/admin/catalog/categories').then(response=>setCategories(response.data.items.filter(item=>item.status==='ACTIVE'))).catch(reason=>setError(reason.message));void loadProduct().catch(reason=>setError(reason.message))},[id]);
  useEffect(()=>{if(!file){setPreviewUrl("");return}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[file]);

  const readiness=useMemo(()=>[
    {label:"Название и описание",ready:Boolean(form.name&&form.shortDescription&&form.description)},
    {label:"Цена",ready:Number(form.price.replace(",","."))>0},
    {label:"Категория",ready:Boolean(form.primaryCategoryId)},
    {label:"Хотя бы один размер",ready:variants.some(item=>item.status==="ACTIVE")},
    {label:"Фотография",ready:media.some(item=>item.primary)},
  ],[form,variants,media]);
  const ready=readiness.every(item=>item.ready);

  const perform=async(action:()=>Promise<void>)=>{setBusy(true);setError("");setMessage("");try{await action()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const chooseFile=(next:File|null)=>{setError("");setUploadProgress(null);setUploadPhase("");if(!next){setFile(null);return}if(!["image/jpeg","image/png","image/webp"].includes(next.type)){setError("Выберите изображение JPG, PNG или WebP");return}if(next.size>10*1024*1024){setError("Фотография должна быть не больше 10 МБ");return}setFile(next)};
  const save=async(event:FormEvent)=>{event.preventDefault();await perform(async()=>{
    const slug=id?form.slug:catalogSlug(form.name);if(!slug)throw new Error("Введите название товара");
    const price=Number(form.price.replace(",","."));
    if(!Number.isFinite(price)||price<=0||Math.round(price*100)!==price*100)throw new Error("Укажите корректную цену, не больше двух знаков после запятой");
    const {price:_price,...productFields}=form;
    const base={...productFields,name:form.name.trim(),slug,priceMinor:Math.round(price*100),categoryIds:[form.primaryCategoryId],collectionIds:[],characteristics:[]};
    if(id){const salePercent=merchandising.onSale?Number(merchandising.salePercent):null;if(merchandising.onSale&&(!Number.isInteger(salePercent)||Number(salePercent)<1||Number(salePercent)>90))throw new Error("Укажите скидку от 1 до 90%");const body={...base,merchandising:{newArrival:merchandising.newArrival,newUntil:merchandising.newArrival&&merchandising.newUntil?new Date(merchandising.newUntil).toISOString():null,onSale:merchandising.onSale,salePercent}};const response=await api<Product>(`/admin/catalog/products/${id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify(body)});setEtag(response.etag);setMessage("Изменения сохранены")}else{const response=await api<Product>("/admin/catalog/products",{method:"POST",headers:commandHeaders(),body:JSON.stringify(base)});window.location.assign(`/admin/catalog/products/${response.data.id}`)}
  })};
  const createVariant=async()=>perform(async()=>{if(!id||!label.trim())return;const sku=`${form.slug}-${catalogSlug(label)}-${Date.now().toString(36)}`.toUpperCase();await api(`/admin/catalog/products/${id}/variants`,{method:"POST",headers:commandHeaders(etag),body:JSON.stringify({sku,label:label.trim(),displayOrder:variants.length,attributes:[{definitionCode:"size",definitionName:"Размер",type:"SIZE",valueCode:catalogSlug(label),label:label.trim()}]})});setLabel("");setMessage("Размер добавлен");await loadProduct()});
  const archiveVariant=async(item:Variant)=>perform(async()=>{if(!id)return;await api(`/admin/catalog/products/${id}/variants/${item.id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify({status:item.status==="ACTIVE"?"ARCHIVED":"ACTIVE"})});setMessage(item.status==="ACTIVE"?"Размер скрыт":"Размер возвращён");await loadProduct()});
  const addMedia=async()=>perform(async()=>{if(!id||!file)return;setUploadProgress(0);setUploadPhase("Подготавливаем загрузку");const upload=await api<Upload>(`/admin/catalog/products/${id}/media/uploads`,{method:"POST",body:JSON.stringify({fileName:file.name,contentType:file.type,size:file.size})});setUploadPhase("Загружаем фотографию");await uploadFile(upload.data.uploadUrl,file,percent=>setUploadProgress(percent));setUploadPhase("Обрабатываем и сохраняем");const image=await createImageBitmap(file);await api(`/admin/catalog/products/${id}/media`,{method:"POST",headers:commandHeaders(etag),body:JSON.stringify({objectKey:upload.data.objectKey,contentType:file.type,width:image.width,height:image.height,alt:form.name,displayOrder:media.length,primary:media.length===0})});image.close();setFile(null);setUploadProgress(100);setUploadPhase("Фотография загружена");setMessage("Фотография добавлена");await loadProduct()});
  const makePrimary=async(item:ProductMedia)=>perform(async()=>{if(!id)return;await api(`/admin/catalog/products/${id}/media/${item.id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify({primary:true})});setMessage("Главная фотография изменена");await loadProduct()});
  const transition=async(action:"publish"|"archive"|"restore")=>perform(async()=>{if(!id||!confirm(action==="publish"?"Опубликовать товар на витрине?":action==="archive"?"Перенести товар в архив?":"Восстановить товар как черновик?"))return;const response=await api<Product>(`/admin/catalog/products/${id}/${action}`,{method:"POST",headers:commandHeaders(etag)});setEtag(response.etag);setStatus(response.data.status);setMessage(action==="publish"?"Товар опубликован":action==="archive"?"Товар перенесён в архив":"Товар восстановлен как черновик")});
  const remove=async()=>perform(async()=>{if(!id||!confirm("Удалить товар навсегда вместе с размерами и фотографиями?"))return;await api<void>(`/admin/catalog/products/${id}`,{method:"DELETE",headers:commandHeaders(etag)});window.location.assign("/admin/catalog")});

  return <><div className={styles.heading}><div><p className={styles.eyebrow}>{id?statusLabel[status]:"Новый товар"}</p><h1>{id?form.name||"Редактирование товара":"Добавить товар"}</h1><p>{id?"Заполните карточку и опубликуйте товар, когда всё будет готово.":"Сначала сохраните основную информацию. Затем добавьте размеры и фотографии."}</p></div></div>
    {error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.message}>{message}</div>}
    <div className={styles.editorLayout}><div>
      <section className={styles.panel}><h2>Цена товара</h2><Field label="Цена, ₽"><input required min="0.01" step="0.01" inputMode="decimal" className={styles.input} type="number" value={form.price} onChange={event=>update("price",event.target.value)} placeholder="Например, 5 490"/><span className={styles.hint}>Одна цена применяется ко всем размерам и вариантам товара.</span></Field></section>
      <form className={styles.panel} onSubmit={save}><h2>1. Информация о товаре</h2><div className={styles.formGrid}><Field label="Название товара"><input required autoFocus={!id} className={styles.input} value={form.name} onChange={event=>update("name",event.target.value)} placeholder="Например, Худи Amra Base"/></Field><Field label="Категория"><select required className={styles.select} value={form.primaryCategoryId} onChange={event=>update("primaryCategoryId",event.target.value)}><option value="">Выберите категорию</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select>{categories.length===0&&<span className={styles.hint}>Сначала опубликуйте хотя бы одну категорию.</span>}</Field><Field label="Короткое описание" full><input required maxLength={500} className={styles.input} value={form.shortDescription} onChange={event=>update("shortDescription",event.target.value)} placeholder="Одно предложение о товаре"/></Field><Field label="Полное описание" full><textarea required maxLength={10000} className={styles.textarea} value={form.description} onChange={event=>update("description",event.target.value)} placeholder="Материал, посадка и особенности товара"/></Field></div><div className={styles.sectionActions}><button className={styles.primary} disabled={busy||categories.length===0}>{busy?"Сохраняем…":id?"Сохранить":"Сохранить и продолжить"}</button></div></form>
      {id&&<><section className={styles.panel}><h2>2. Продвижение на витрине</h2><p className={styles.hint}>Эти настройки не влияют на публикацию товара и могут меняться отдельно.</p><div className={styles.promotionGrid}><label className={styles.promotionCard}><input type="checkbox" checked={merchandising.newArrival} onChange={event=>updateMerchandising({newArrival:event.target.checked,newUntil:event.target.checked?merchandising.newUntil:""})}/><span><strong>Новинка</strong><small>Показывать бейдж и добавлять товар в подборку новинок.</small></span></label>{merchandising.newArrival&&<Field label="Показывать как новинку до"><input className={styles.input} type="datetime-local" value={merchandising.newUntil} onChange={event=>updateMerchandising({newUntil:event.target.value})}/><span className={styles.hint}>Оставьте пустым, чтобы отключить вручную позже.</span></Field>}<label className={styles.promotionCard}><input type="checkbox" checked={merchandising.onSale} onChange={event=>updateMerchandising({onSale:event.target.checked,salePercent:event.target.checked?merchandising.salePercent:""})}/><span><strong>Распродажа</strong><small>Показывать товар со скидкой в распродажных подборках.</small></span></label>{merchandising.onSale&&<Field label="Размер скидки, %"><input required min={1} max={90} className={styles.input} type="number" value={merchandising.salePercent} onChange={event=>updateMerchandising({salePercent:event.target.value})} placeholder="Например, 20"/></Field>}</div></section>
      <section className={styles.panel}><h2>3. Размеры</h2><div className={styles.inlineForm}><input className={styles.input} value={label} onChange={event=>setLabel(event.target.value)} placeholder="Например, M или 42"/><button type="button" disabled={busy||!label.trim()} className={styles.secondary} onClick={()=>void createVariant()}>Добавить</button></div><div className={styles.chipList}>{variants.map(item=><div className={`${styles.chip} ${item.status==="ARCHIVED"?styles.chipMuted:""}`} key={item.id}><span>{item.label}</span><button disabled={busy} onClick={()=>void archiveVariant(item)}>{item.status==="ACTIVE"?"Скрыть":"Вернуть"}</button></div>)}{variants.length===0&&<p className={styles.hint}>Размеры пока не добавлены.</p>}</div></section>
      <section className={styles.panel}><h2>4. Фотографии</h2><p className={styles.hint}>Добавьте качественную фотографию товара. Первая загруженная фотография станет главной.</p>{!file?<label className={`${styles.photoDropzone} ${draggingFile?styles.photoDropzoneActive:""}`} onDragEnter={event=>{event.preventDefault();setDraggingFile(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDraggingFile(false)} onDrop={event=>{event.preventDefault();setDraggingFile(false);chooseFile(event.dataTransfer.files[0]??null)}}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>chooseFile(event.target.files?.[0]??null)}/><span className={styles.photoDropzoneIcon} aria-hidden="true">＋</span><strong>Перетащите фотографию сюда</strong><span>или нажмите, чтобы выбрать файл</span><small>JPG, PNG или WebP · до 10 МБ</small><b>Выбрать фотографию</b></label>:<div className={styles.selectedPhoto}>{previewUrl&&<img src={previewUrl} alt="Предпросмотр выбранной фотографии"/>}<div><span className={styles.eyebrow}>Выбрана фотография</span><strong>{file.name}</strong><small>{formatFileSize(file.size)}</small><div className={styles.selectedPhotoActions}><label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>chooseFile(event.target.files?.[0]??null)}/>Заменить</label><button type="button" disabled={busy} onClick={()=>chooseFile(null)}>Убрать</button></div></div></div>} {file&&<button type="button" disabled={busy} className={`${styles.primary} ${styles.uploadPhotoButton}`} onClick={()=>void addMedia()}>{busy&&uploadProgress!==null?"Загружаем фотографию…":"Загрузить фотографию"}</button>}{uploadProgress!==null&&<div className={styles.uploadProgress} role="status" aria-live="polite"><div><span>{uploadPhase}</span><strong>{uploadProgress}%</strong></div><progress max={100} value={uploadProgress}/></div>}<div className={styles.mediaList}>{media.map((item,index)=><div className={styles.mediaItem} key={item.id}><div><strong>Фотография {index+1}</strong><span>{item.width} × {item.height}</span></div>{item.primary?<span className={`${styles.badge} ${styles.active}`}>Главная</span>:<button className={styles.textButton} disabled={busy} onClick={()=>void makePrimary(item)}>Сделать главной</button>}</div>)}{media.length===0&&<p className={styles.hint}>Загруженных фотографий пока нет.</p>}</div></section></>}
    </div>{id&&<aside className={styles.readiness}><h2>{status==="ARCHIVED"?"Товар в архиве":"Готовность товара"}</h2>{status!=="ARCHIVED"&&readiness.map(item=><div className={item.ready?styles.ready:styles.notReady} key={item.label}><span>{item.ready?"✓":"○"}</span>{item.label}</div>)}<p>{status==="ARCHIVED"?"Товар не показывается на витрине и убран из рабочего списка.":ready?"Карточка готова к публикации.":"Заполните недостающие пункты."}</p>{status==="ARCHIVED"?<><button className={styles.primary} disabled={busy} onClick={()=>void transition("restore")}>Восстановить</button><button className={styles.danger} disabled={busy} onClick={()=>void remove()}>Удалить навсегда</button></>:<>{status==="ACTIVE"?<button className={styles.danger} disabled={busy} onClick={()=>void transition("archive")}>Убрать в архив</button>:<><button className={styles.primary} disabled={busy||!ready} onClick={()=>void transition("publish")}>Опубликовать товар</button><button className={styles.secondary} disabled={busy} onClick={()=>void transition("archive")}>Убрать в архив</button></>}</>}</aside>}</div>
  </>;
}

function Field({label,full=false,children}:{label:string;full?:boolean;children:React.ReactNode}){return <div className={`${styles.field} ${full?styles.full:""}`}><label>{label}</label>{children}</div>}

function toLocalDateTime(value:string){const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}

function formatFileSize(bytes:number){return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} МБ`:`${Math.ceil(bytes/1024)} КБ`}

function uploadFile(url:string,file:File,onProgress:(percent:number)=>void){return new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();request.open("PUT",url);request.setRequestHeader("Content-Type",file.type);request.upload.addEventListener("progress",event=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))});request.addEventListener("load",()=>request.status>=200&&request.status<300?resolve():reject(new Error("Не удалось загрузить фотографию")));request.addEventListener("error",()=>reject(new Error("Соединение прервалось во время загрузки")));request.addEventListener("abort",()=>reject(new Error("Загрузка фотографии отменена")));request.send(file)})}
