"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, jsx-a11y/label-has-associated-control */
import {FormEvent,useEffect,useMemo,useState} from "react";
import {api,commandHeaders,StockItem,WarehouseOverview} from "../api";
import styles from "../admin.module.css";

type View="stock"|"receipt"|"adjust"|"movements";
type ReceiptLine={variantId:string;quantity:number;idempotencyKey:string};
const movementNames:Record<string,string>={RECEIPT:"Приёмка",ADJUSTMENT_INCREASE:"Корректировка +",ADJUSTMENT_DECREASE:"Корректировка −",RESERVATION_COMMIT:"Продажа",RETURN:"Возврат"};

export default function Inventory(){
  const [data,setData]=useState<WarehouseOverview|null>(null),[view,setView]=useState<View>("stock"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState(""),[quantity,setQuantity]=useState("1"),[reference,setReference]=useState(""),[lines,setLines]=useState<ReceiptLine[]>([]);
  const [adjustId,setAdjustId]=useState(""),[observed,setObserved]=useState("0"),[reason,setReason]=useState("Пересчёт фактического остатка");
  const load=async()=>{try{setError("");setData((await api<WarehouseOverview>("/admin/inventory")).data)}catch(e){setError((e as Error).message)}};
  useEffect(()=>{void load()},[]);
  const items=data?.items??[];
  const visible=useMemo(()=>items.filter(item=>{const text=`${item.productName} ${item.sku} ${item.variantLabel}`.toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;if(filter==="in")return item.available>5;if(filter==="low")return item.available>0&&item.available<=5;if(filter==="out")return item.available===0;return true}),[items,query,filter]);
  const totals=useMemo(()=>({onHand:items.reduce((n,x)=>n+x.onHand,0),reserved:items.reduce((n,x)=>n+x.reserved,0),available:items.reduce((n,x)=>n+x.available,0),low:items.filter(x=>x.available>0&&x.available<=5).length,out:items.filter(x=>x.available===0).length}),[items]);
  const chooseAdjust=(item:StockItem)=>{setAdjustId(item.variantId);setObserved(String(item.onHand));setView("adjust");setMessage("")};
  const addLine=(event:FormEvent)=>{event.preventDefault();const amount=Number(quantity);if(!selected||!Number.isInteger(amount)||amount<1)return;setLines(current=>{const found=current.find(x=>x.variantId===selected);return found?current.map(x=>x.variantId===selected?{...x,quantity:x.quantity+amount,idempotencyKey:crypto.randomUUID()}:x):[...current,{variantId:selected,quantity:amount,idempotencyKey:crypto.randomUUID()}]});setQuantity("1")};
  const receive=async()=>{if(!lines.length)return;try{setBusy(true);setError("");for(const line of lines){await api(`/admin/inventory/balances/${line.variantId}/receipts`,{method:"POST",headers:{"Idempotency-Key":line.idempotencyKey},body:JSON.stringify({quantity:line.quantity,reason:"Свободная приёмка",reference:reference||undefined})})}const received=lines.reduce((n,x)=>n+x.quantity,0);setLines([]);setReference("");setMessage(`Приёмка проведена: ${received} ед.`);await load();setView("stock")}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  const adjust=async()=>{const item=items.find(x=>x.variantId===adjustId);if(!item)return;try{setBusy(true);setError("");await api(`/admin/inventory/balances/${item.variantId}/adjustments`,{method:"POST",headers:commandHeaders(`"v${item.version}"`),body:JSON.stringify({onHand:Number(observed),reason})});setMessage("Фактический остаток зафиксирован");await load();setView("stock")}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  const lineItem=(id:string)=>items.find(x=>x.variantId===id);
  return <>
    <div className={styles.heading}><div><p className={styles.eyebrow}>Основной склад</p><h1>Склад</h1><p>Остатки, свободная приёмка и история физических движений.</p></div><button className={styles.primary} onClick={()=>setView("receipt")}>+ Новая приёмка</button></div>
    {error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.message}>{message}</div>}
    <div className={styles.inventoryMetrics}><article><span>На складе</span><strong>{totals.onHand}</strong><small>физических единиц</small></article><article><span>В резерве</span><strong>{totals.reserved}</strong><small>под заказы</small></article><article><span>Доступно</span><strong>{totals.available}</strong><small>к продаже</small></article><article><span>Требуют внимания</span><strong>{totals.low+totals.out}</strong><small>{totals.out} без остатка</small></article></div>
    <nav className={styles.viewTabs} aria-label="Разделы склада"><button className={view==="stock"?styles.viewTabActive:undefined} onClick={()=>setView("stock")}>Остатки</button><button className={view==="receipt"?styles.viewTabActive:undefined} onClick={()=>setView("receipt")}>Приёмка {lines.length?`· ${lines.length}`:""}</button><button className={view==="adjust"?styles.viewTabActive:undefined} onClick={()=>setView("adjust")}>Корректировка</button><button className={view==="movements"?styles.viewTabActive:undefined} onClick={()=>setView("movements")}>Движения</button></nav>
    {view==="stock"&&<><div className={styles.inventoryToolbar}><input className={styles.input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, вариант или SKU"/><select className={styles.select} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все позиции</option><option value="in">В наличии</option><option value="low">Заканчиваются</option><option value="out">Нет в наличии</option></select></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Товар</th><th>Вариант</th><th>SKU</th><th>На складе</th><th>Резерв</th><th>Доступно</th><th></th></tr></thead><tbody>{visible.map(item=><tr key={item.variantId}><td><a href={`/admin/catalog/products/${item.productId}`}>{item.productName}</a>{item.productStatus==="DRAFT"&&<div className={styles.slug}>Черновик карточки</div>}</td><td>{item.variantLabel}</td><td><code>{item.sku}</code></td><td>{item.onHand}</td><td>{item.reserved}</td><td><span className={`${styles.stockState} ${item.available===0?styles.stockOut:item.available<=5?styles.stockLow:styles.stockOk}`}>{item.available}</span></td><td><button className={styles.rowButton} onClick={()=>chooseAdjust(item)}>Сверить →</button></td></tr>)}</tbody></table>{visible.length===0&&<div className={styles.empty}>Подходящих складских позиций нет.</div>}</div></>}
    {view==="receipt"&&<section className={styles.panel}><div className={styles.panelHeading}><div><h2>Свободная приёмка</h2><p className={styles.hint}>Добавьте существующие варианты и фактически принятое количество.</p></div><a className={styles.secondary} href="/admin/catalog/products/new">+ Создать черновик товара</a></div><form className={styles.receiptComposer} onSubmit={addLine}><select required className={styles.select} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите товар и вариант</option>{items.map(item=><option key={item.variantId} value={item.variantId}>{item.productName} · {item.variantLabel} · {item.sku}</option>)}</select><input className={styles.input} type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button className={styles.secondary}>Добавить</button></form>{lines.length?<><div className={styles.receiptLines}>{lines.map(line=>{const item=lineItem(line.variantId);return <div key={line.variantId}><span><strong>{item?.productName}</strong><small>{item?.variantLabel} · {item?.sku}</small></span><b>+{line.quantity}</b><button onClick={()=>setLines(x=>x.filter(y=>y.variantId!==line.variantId))}>Удалить</button></div>})}</div><div className={styles.formGrid}><div className={styles.field}><label>Комментарий или номер накладной</label><input className={styles.input} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Необязательно"/></div></div><div className={styles.sectionActions}><button disabled={busy} className={styles.primary} onClick={()=>void receive()}>{busy?"Проводим…":"Провести приёмку"}</button></div></>:<div className={styles.empty}>Добавьте хотя бы одну позицию.</div>}</section>}
    {view==="adjust"&&<section className={styles.panel}><h2>Корректировка по факту</h2><p className={styles.hint}>Укажите количество, которое сотрудник пересчитал физически. Система сама запишет разницу движением.</p><div className={styles.formGrid}><div className={styles.field}><label>Товар и вариант</label><select className={styles.select} value={adjustId} onChange={e=>{setAdjustId(e.target.value);const x=items.find(i=>i.variantId===e.target.value);if(x)setObserved(String(x.onHand))}}><option value="">Выберите позицию</option>{items.map(item=><option key={item.variantId} value={item.variantId}>{item.productName} · {item.variantLabel}</option>)}</select></div><div className={styles.field}><label>Фактически на складе</label><input className={styles.input} type="number" min="0" value={observed} onChange={e=>setObserved(e.target.value)}/></div><div className={`${styles.field} ${styles.full}`}><label>Причина</label><input className={styles.input} value={reason} onChange={e=>setReason(e.target.value)}/></div></div><div className={styles.sectionActions}><button disabled={busy||!adjustId} className={styles.primary} onClick={()=>void adjust()}>{busy?"Сохраняем…":"Зафиксировать остаток"}</button></div></section>}
    {view==="movements"&&<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Дата</th><th>Товар</th><th>Операция</th><th>Изменение</th><th>Причина</th><th>Документ</th></tr></thead><tbody>{data?.movements.map(m=><tr key={m.id}><td>{new Date(m.occurredAt).toLocaleString("ru-RU")}</td><td><strong>{m.productName}</strong><div className={styles.slug}>{m.variantLabel} · {m.sku}</div></td><td>{movementNames[m.type]??m.type}</td><td><b className={m.quantityDelta>0?styles.deltaPositive:styles.deltaNegative}>{m.quantityDelta>0?"+":""}{m.quantityDelta}</b></td><td>{m.reason}</td><td>{m.reference??"—"}</td></tr>)}</tbody></table>{data?.movements.length===0&&<div className={styles.empty}>Движений пока нет.</div>}</div>}
  </>;
}
