"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Category, commandHeaders, Product, ProductMedia, Variant } from "../../api";
import { catalogSlug } from "../../catalog-slug";
import styles from "../../admin.module.css";

type Form = { name:string; slug:string; shortDescription:string; description:string; price:string; primaryCategoryId:string };
type MerchandisingForm = { newArrival:boolean; newUntil:string; onSale:boolean; salePercent:string; featured:boolean };
type Upload = { objectKey:string; uploadUrl:string; contentType:string };
const empty:Form = { name:"", slug:"", shortDescription:"", description:"", price:"", primaryCategoryId:"" };
const emptyMerchandising:MerchandisingForm = { newArrival:false, newUntil:"", onSale:false, salePercent:"", featured:false };
const statusLabel={DRAFT:"Черновик",ACTIVE:"Опубликован",ARCHIVED:"В архиве"} as const;

export default function ProductEditor({ id }: { id?:string }) {
  const [form,setForm]=useState<Form>(empty), [categories,setCategories]=useState<Category[]>([]), [variants,setVariants]=useState<Variant[]>([]), [media,setMedia]=useState<ProductMedia[]>([]);
  const [merchandising,setMerchandising]=useState<MerchandisingForm>(emptyMerchandising);
  const [etag,setEtag]=useState<string|null>(null), [status,setStatus]=useState<Product["status"]>("DRAFT");
  const [error,setError]=useState(""), [message,setMessage]=useState(""), [busy,setBusy]=useState(false);
  const [sizeLabel,setSizeLabel]=useState(""), [colorLabel,setColorLabel]=useState(""), [colorHex,setColorHex]=useState("#202226"), [mediaColor,setMediaColor]=useState(""), [file,setFile]=useState<File|null>(null);
  const [uploadProgress,setUploadProgress]=useState<number|null>(null), [uploadPhase,setUploadPhase]=useState("");
  const [previewUrl,setPreviewUrl]=useState(""), [draggingFile,setDraggingFile]=useState(false);
  const [hasAvailableStock,setHasAvailableStock]=useState<boolean|null>(null);
  const [savedSnapshot,setSavedSnapshot]=useState(()=>JSON.stringify([empty,emptyMerchandising]));
  const update=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  const updateMerchandising=(patch:Partial<MerchandisingForm>)=>setMerchandising(current=>({...current,...patch}));
  const loadProduct=async()=>{if(!id)return;const response=await api<Product>(`/admin/catalog/products/${id}`);const nextForm={name:response.data.name,slug:response.data.slug,shortDescription:response.data.shortDescription,description:response.data.description,price:response.data.priceMinor?String(response.data.priceMinor/100):"",primaryCategoryId:response.data.primaryCategoryId};const promo=response.data.merchandising,nextMerchandising={newArrival:promo?.newArrival??false,newUntil:promo?.newUntil?toLocalDateTime(promo.newUntil):"",onSale:promo?.onSale??false,salePercent:promo?.salePercent?String(promo.salePercent):"",featured:promo?.featured??false};setForm(nextForm);setMerchandising(nextMerchandising);setSavedSnapshot(JSON.stringify([nextForm,nextMerchandising]));setStatus(response.data.status);setVariants(response.data.variants??[]);setMedia(response.data.media??[]);setEtag(response.etag)};
  useEffect(()=>{void api<{items:Category[]}>('/admin/catalog/categories').then(response=>setCategories(response.data.items.filter(item=>item.status==='ACTIVE'))).catch(reason=>setError(reason.message));void loadProduct().catch(reason=>setError(reason.message))},[id]);
  useEffect(()=>{if(!file){setPreviewUrl("");return}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{const ids=variants.filter(item=>item.status==="ACTIVE").map(item=>item.id);if(ids.length===0){setHasAvailableStock(false);return}const query=ids.map(variantId=>`variantId=${encodeURIComponent(variantId)}`).join("&");void api<{items:Array<{status:string}>}>(`/inventory/availability?${query}`).then(response=>setHasAvailableStock(response.data.items.some(item=>item.status==="IN_STOCK"))).catch(()=>setHasAvailableStock(null))},[variants]);
  const dirty=JSON.stringify([form,merchandising])!==savedSnapshot;
  useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(!dirty)return;event.preventDefault()};window.addEventListener("beforeunload",protect);return()=>window.removeEventListener("beforeunload",protect)},[dirty]);

  const readiness=useMemo(()=>[
    {label:"Название и описание",ready:Boolean(form.name&&form.shortDescription&&form.description)},
    {label:"Цена",ready:Number(form.price.replace(",","."))>0},
    {label:"Категория",ready:Boolean(form.primaryCategoryId)},
    {label:"Хотя бы один размер",ready:variants.some(item=>item.status==="ACTIVE")},
    {label:"Фотография",ready:media.some(item=>item.primary)},
  ],[form,variants,media]);
  const ready=readiness.every(item=>item.ready);

  const perform=async(action:()=>Promise<void>)=>{setBusy(true);setError("");setMessage("");try{await action()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const chooseFile=(next:File|null)=>{setError("");setUploadProgress(null);setUploadPhase("");if(!next){setFile(null);return}if(!["image/jpeg","image/png","image/webp"].includes(next.type)){setError("Выберите изображение JPG, PNG или WebP");return}if(next.size>10*1024*1024){setError("Фотография должна быть не больше 10 МБ");return}setFile(next)};
  const save=async(event:FormEvent)=>{event.preventDefault();await perform(async()=>{
    const slug=id?form.slug:catalogSlug(form.name);if(!slug)throw new Error("Введите название товара");
    if(!form.primaryCategoryId)throw new Error("Выберите категорию товара");
    if(!form.shortDescription.trim()||!form.description.trim())throw new Error("Заполните короткое и полное описание товара");
    const price=Number(form.price.replace(",","."));
    if(!Number.isFinite(price)||price<=0||Math.round(price*100)!==price*100)throw new Error("Укажите корректную цену, не больше двух знаков после запятой");
    const base={name:form.name.trim(),slug,shortDescription:form.shortDescription,description:form.description,primaryCategoryId:form.primaryCategoryId,priceMinor:Math.round(price*100),categoryIds:[form.primaryCategoryId],collectionIds:[],characteristics:[]};
    if(id){const salePercent=merchandising.onSale?Number(merchandising.salePercent):null;if(merchandising.onSale&&(!Number.isInteger(salePercent)||Number(salePercent)<1||Number(salePercent)>90))throw new Error("Укажите скидку от 1 до 90%");const body={...base,merchandising:{newArrival:merchandising.newArrival,newUntil:merchandising.newArrival&&merchandising.newUntil?new Date(merchandising.newUntil).toISOString():null,onSale:merchandising.onSale,salePercent,featured:merchandising.featured}};const response=await api<Product>(`/admin/catalog/products/${id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify(body)});setEtag(response.etag);setSavedSnapshot(JSON.stringify([form,merchandising]));setMessage("Все изменения сохранены")}else{const response=await api<Product>("/admin/catalog/products",{method:"POST",headers:commandHeaders(),body:JSON.stringify(base)});window.location.assign(`/admin/catalog/products/${response.data.id}`)}
  })};
  const colorOf=(item:Variant)=>item.attributes.find(attribute=>attribute.type==="COLOR");
  const sizeOf=(item:Variant)=>item.attributes.find(attribute=>attribute.type==="SIZE");
  const colors=Array.from(new Map(variants.flatMap(item=>{const color=colorOf(item);return color?[[color.valueCode,color] as const]:[]})).values());
  const sizes=Array.from(new Map(variants.flatMap(item=>{const size=sizeOf(item);return size?[[size.valueCode,size] as const]:[]})).values());
  const createCombination=async(color:{valueCode:string;label:string;colorHex?:string|null}|null,size:{valueCode:string;label:string},currentEtag:string|null,order:number)=>{const attributes=[...(color?[{definitionCode:"color",definitionName:"Цвет",type:"COLOR",valueCode:color.valueCode,label:color.label,colorHex:color.colorHex}]:[]),{definitionCode:"size",definitionName:"Размер",type:"SIZE",valueCode:size.valueCode,label:size.label}];const sku=[form.slug,color?.valueCode,size.valueCode,Date.now().toString(36),order].filter(Boolean).join("-").toUpperCase();return api<Variant>(`/admin/catalog/products/${id}/variants`,{method:"POST",headers:commandHeaders(currentEtag),body:JSON.stringify({sku,label:[color?.label,size.label].filter(Boolean).join(" · "),displayOrder:order,attributes})})};
  const addSize=async()=>perform(async()=>{if(!id)return;if(!sizeLabel.trim())throw new Error("Введите название размера");const size={valueCode:catalogSlug(sizeLabel),label:sizeLabel.trim()};if(sizes.some(item=>item.valueCode===size.valueCode))throw new Error("Такой размер уже добавлен");let currentEtag=etag;const targets=colors.length?colors:[null];for(const color of targets){const response=await createCombination(color,size,currentEtag,variants.length);currentEtag=response.etag}setSizeLabel("");setMessage("Размер добавлен для всех цветов");await loadProduct()});
  const addColor=async()=>perform(async()=>{if(!id)return;if(!colorLabel.trim())throw new Error("Введите название цвета");if(sizes.length===0)throw new Error("Сначала добавьте хотя бы один размер");const color={valueCode:catalogSlug(colorLabel),label:colorLabel.trim(),colorHex};if(colors.some(item=>item.valueCode===color.valueCode))throw new Error("Такой цвет уже добавлен");let currentEtag=etag;for(const size of sizes){const response=await createCombination(color,size,currentEtag,variants.length);currentEtag=response.etag}if(colors.length===0){for(const item of variants.filter(variant=>!colorOf(variant)&&variant.status==="ACTIVE")){const response=await api<Variant>(`/admin/catalog/products/${id}/variants/${item.id}`,{method:"PATCH",headers:commandHeaders(currentEtag),body:JSON.stringify({status:"ARCHIVED"})});currentEtag=response.etag}}setColorLabel("");setMessage("Цвет добавлен, варианты созданы автоматически");await loadProduct()});
  const archiveVariant=async(item:Variant)=>perform(async()=>{if(!id)return;await api(`/admin/catalog/products/${id}/variants/${item.id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify({status:item.status==="ACTIVE"?"ARCHIVED":"ACTIVE"})});setMessage(item.status==="ACTIVE"?"Размер скрыт":"Размер возвращён");await loadProduct()});
  const addMedia=async()=>perform(async()=>{if(!id||!file)return;setUploadProgress(0);setUploadPhase("Подготавливаем загрузку");const upload=await api<Upload>(`/admin/catalog/products/${id}/media/uploads`,{method:"POST",body:JSON.stringify({fileName:file.name,contentType:file.type,size:file.size})});setUploadPhase("Загружаем фотографию");await uploadFile(upload.data.uploadUrl,file,percent=>setUploadProgress(percent));setUploadPhase("Обрабатываем и сохраняем");const image=await createImageBitmap(file);const colorVariant=mediaColor?variants.find(item=>colorOf(item)?.valueCode===mediaColor):undefined;await api(`/admin/catalog/products/${id}/media`,{method:"POST",headers:commandHeaders(etag),body:JSON.stringify({variantId:colorVariant?.id??null,objectKey:upload.data.objectKey,contentType:file.type,width:image.width,height:image.height,alt:form.name,displayOrder:media.length,primary:media.length===0})});image.close();setFile(null);setUploadProgress(100);setUploadPhase("Фотография загружена");setMessage("Фотография добавлена");await loadProduct()});
  const makePrimary=async(item:ProductMedia)=>perform(async()=>{if(!id)return;await api(`/admin/catalog/products/${id}/media/${item.id}`,{method:"PATCH",headers:commandHeaders(etag),body:JSON.stringify({primary:true})});setMessage("Главная фотография изменена");await loadProduct()});
  const deleteMedia=async(item:ProductMedia)=>perform(async()=>{if(!id||!confirm(`Удалить фотографию «${item.alt}»? Это действие нельзя отменить.`))return;await api(`/admin/catalog/products/${id}/media/${item.id}`,{method:"DELETE",headers:commandHeaders(etag)});setMessage("Фотография удалена");await loadProduct()});
  const transition=async(action:"publish"|"archive"|"restore")=>perform(async()=>{if(!id)return;if(action==="publish"&&!ready)throw new Error(`Чтобы опубликовать товар, добавьте: ${readiness.filter(item=>!item.ready).map(item=>item.label.toLocaleLowerCase("ru")).join(", ")}.`);if(action==="publish"&&dirty)throw new Error("Сначала сохраните изменения в карточке товара");const publishQuestion=hasAvailableStock===false?"На складе нет доступного остатка. Товар будет виден как отсутствующий. Всё равно опубликовать?":"Опубликовать товар на витрине?";if(!confirm(action==="publish"?publishQuestion:action==="archive"?"Перенести товар в архив?":"Восстановить товар как черновик?"))return;const response=await api<Product>(`/admin/catalog/products/${id}/${action}`,{method:"POST",headers:commandHeaders(etag)});setEtag(response.etag);setStatus(response.data.status);setMessage(action==="publish"?"Товар опубликован":action==="archive"?"Товар перенесён в архив":"Товар восстановлен как черновик")});
  const remove=async()=>perform(async()=>{if(!id||!confirm("Удалить товар навсегда вместе с размерами и фотографиями?"))return;await api<void>(`/admin/catalog/products/${id}`,{method:"DELETE",headers:commandHeaders(etag)});window.location.assign("/admin/catalog")});

  return <><div className={styles.heading}><div><p className={styles.eyebrow}>{id?statusLabel[status]:"Новый товар"}</p><h1>{id?form.name||"Редактирование товара":"Добавить товар"}</h1><p>{id?"Заполните карточку и опубликуйте товар, когда всё будет готово.":"Сначала сохраните основную информацию. Затем добавьте размеры и фотографии."}</p></div></div>
    <div className={styles.editorSaveBar}><span className={dirty?styles.unsavedState:styles.savedState}>{dirty?"Есть несохранённые изменения":"Все изменения сохранены"}</span><button form="product-main-form" className={styles.primary} disabled={busy||!dirty}>{busy?"Сохраняем…":id?"Сохранить изменения":"Сохранить и продолжить"}</button></div>
    {error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.message}>{message}</div>}
    {id&&media.length>0&&<CollapsibleSection title={`Загруженные фотографии · ${media.length}`}><p className={styles.hint}>Главная фотография показывается первой на витрине.</p><div className={styles.mediaGallery}>{media.map((item,index)=><article className={styles.mediaPreview} key={item.id}><div className={styles.mediaPreviewImage}><img src={item.deliveryUrl} alt={item.alt}/>{item.primary&&<span className={`${styles.badge} ${styles.active}`}>Главная</span>}</div><div className={styles.mediaPreviewInfo}><strong>Фотография {index+1}</strong><span>{item.width} × {item.height}</span></div><div className={styles.mediaPreviewActions}>{!item.primary&&<button type="button" className={styles.textButton} disabled={busy} onClick={()=>void makePrimary(item)}>Сделать главной</button>}<button type="button" className={styles.mediaDelete} disabled={busy} onClick={()=>void deleteMedia(item)}>Удалить</button></div></article>)}</div></CollapsibleSection>}
    <div className={styles.editorLayout}><div>
      <CollapsibleSection title="1. Информация о товаре"><form id="product-main-form" noValidate onSubmit={save}><div className={styles.formGrid}><Field label="Название товара"><input required autoFocus={!id} className={styles.input} value={form.name} onChange={event=>update("name",event.target.value)} placeholder="Например, Худи Amra Base"/></Field><Field label="Категория"><select required className={styles.select} value={form.primaryCategoryId} onChange={event=>update("primaryCategoryId",event.target.value)}><option value="">Выберите категорию</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select>{categories.length===0&&<span className={styles.hint}>Сначала <a href="/admin/catalog/categories">создайте и опубликуйте категорию</a>.</span>}</Field><Field label="Короткое описание" full><input required maxLength={500} className={styles.input} value={form.shortDescription} onChange={event=>update("shortDescription",event.target.value)} placeholder="Одно предложение о товаре"/></Field><Field label="Полное описание" full><textarea required maxLength={10000} className={styles.textarea} value={form.description} onChange={event=>update("description",event.target.value)} placeholder="Материал, посадка и особенности товара"/></Field></div></form></CollapsibleSection>
      <CollapsibleSection title="2. Цена"><Field label="Цена, ₽"><input required min="0.01" step="0.01" inputMode="decimal" className={styles.input} type="number" value={form.price} onChange={event=>update("price",event.target.value)} placeholder="Например, 5 490"/><span className={styles.hint}>Одна цена применяется ко всем размерам и вариантам товара.</span></Field></CollapsibleSection>
      {id&&<><CollapsibleSection title="3. Продвижение на витрине"><p className={styles.hint}>Эти настройки сохраняются вместе с основной информацией.</p><div className={styles.promotionGrid}><label className={styles.promotionCard}><input type="checkbox" checked={merchandising.newArrival} onChange={event=>updateMerchandising({newArrival:event.target.checked,newUntil:event.target.checked?merchandising.newUntil:""})}/><span><strong>Новинка</strong><small>Показывать бейдж и добавлять товар в подборку новинок.</small></span></label>{merchandising.newArrival&&<Field label="Показывать как новинку до"><input className={styles.input} type="datetime-local" value={merchandising.newUntil} onChange={event=>updateMerchandising({newUntil:event.target.value})}/><span className={styles.hint}>Оставьте пустым, чтобы отключить вручную позже.</span></Field>}<label className={styles.promotionCard}><input type="checkbox" checked={merchandising.onSale} onChange={event=>updateMerchandising({onSale:event.target.checked,salePercent:event.target.checked?merchandising.salePercent:""})}/><span><strong>Распродажа</strong><small>Показывать товар со скидкой в распродажных подборках.</small></span></label>{merchandising.onSale&&<Field label="Размер скидки, %"><input required min={1} max={90} className={styles.input} type="number" value={merchandising.salePercent} onChange={event=>updateMerchandising({salePercent:event.target.value})} placeholder="Например, 20"/></Field>}<label className={styles.promotionCard}><input type="checkbox" checked={merchandising.featured} onChange={event=>updateMerchandising({featured:event.target.checked})}/><span><strong>Товар недели</strong><small>Показывать товар в редакционной подборке на главной странице.</small></span></label></div></CollapsibleSection>
      <CollapsibleSection title="4. Цвета и размеры"><p className={styles.hint}>Сначала добавьте размеры, затем цвета. Для каждого цвета автоматически создаются все комбинации размеров.</p><div className={styles.variantBuilders}><div><strong>Размеры</strong><div className={styles.inlineForm}><input className={styles.input} value={sizeLabel} onChange={event=>setSizeLabel(event.target.value)} placeholder="Например, M или 42"/><button type="button" disabled={busy} className={styles.secondary} onClick={()=>void addSize()}>Добавить размер</button></div></div><div><strong>Цвета</strong><div className={styles.colorForm}><input className={styles.colorPicker} type="color" value={colorHex} onChange={event=>setColorHex(event.target.value)}/><input className={styles.input} value={colorLabel} onChange={event=>setColorLabel(event.target.value)} placeholder="Например, Графит"/><button type="button" disabled={busy} className={styles.secondary} onClick={()=>void addColor()}>Добавить цвет</button></div></div></div>{colors.length>0&&<div className={styles.colorLegend}>{colors.map(color=><span key={color.valueCode}><i style={{background:color.colorHex??"#ccc"}}/>{color.label}</span>)}</div>}<div className={styles.variantMatrix}>{variants.filter(item=>colorOf(item)||colors.length===0).map(item=><div className={`${styles.variantRow} ${item.status==="ARCHIVED"?styles.chipMuted:""}`} key={item.id}><span className={styles.variantColor} style={{background:colorOf(item)?.colorHex??"#ddd"}}/><div><strong>{colorOf(item)?.label??"Без цвета"} · {sizeOf(item)?.label??item.label}</strong><small>{item.sku}</small></div><button disabled={busy} onClick={()=>void archiveVariant(item)}>{item.status==="ACTIVE"?"Скрыть":"Вернуть"}</button></div>)}{variants.length===0&&<p className={styles.hint}>Добавьте первый размер.</p>}</div></CollapsibleSection>
      <CollapsibleSection title="5. Фотографии"><p className={styles.hint}>Добавьте качественную фотографию товара. Первая загруженная фотография станет главной.</p>{colors.length>0&&<div className={styles.mediaColorPanel}><label>Для какого цвета эта фотография?<select className={styles.select} value={mediaColor} onChange={event=>setMediaColor(event.target.value)}><option value="">Общая фотография товара</option>{colors.map(color=><option value={color.valueCode} key={color.valueCode}>{color.label}</option>)}</select></label><span>Выберите цвет до загрузки. Если фото подходит всем цветам, оставьте «Общая фотография товара».</span></div>}{!file?<label className={`${styles.photoDropzone} ${draggingFile?styles.photoDropzoneActive:""}`} onDragEnter={event=>{event.preventDefault();setDraggingFile(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDraggingFile(false)} onDrop={event=>{event.preventDefault();setDraggingFile(false);chooseFile(event.dataTransfer.files[0]??null)}}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>chooseFile(event.target.files?.[0]??null)}/><span className={styles.photoDropzoneIcon} aria-hidden="true">＋</span><strong>Перетащите фотографию сюда</strong><span>или нажмите, чтобы выбрать файл</span><small>JPG, PNG или WebP · до 10 МБ</small><b>Выбрать фотографию</b></label>:<div className={styles.selectedPhoto}>{previewUrl&&<img src={previewUrl} alt="Предпросмотр выбранной фотографии"/>}<div><span className={styles.eyebrow}>Выбрана фотография</span><strong>{file.name}</strong><small>{formatFileSize(file.size)}</small><div className={styles.selectedPhotoActions}><label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>chooseFile(event.target.files?.[0]??null)}/>Заменить</label><button type="button" disabled={busy} onClick={()=>chooseFile(null)}>Убрать</button></div></div></div>} {file&&<button type="button" disabled={busy} className={`${styles.primary} ${styles.uploadPhotoButton}`} onClick={()=>void addMedia()}>{busy&&uploadProgress!==null?"Загружаем фотографию…":"Загрузить фотографию"}</button>}{uploadProgress!==null&&<div className={styles.uploadProgress} role="status" aria-live="polite"><div><span>{uploadPhase}</span><strong>{uploadProgress}%</strong></div><progress max={100} value={uploadProgress}/></div>}<div className={styles.mediaList}>{media.map((item,index)=><div className={styles.mediaItem} key={item.id}><div><strong>Фотография {index+1}</strong><span>{item.width} × {item.height}</span></div>{item.primary?<span className={`${styles.badge} ${styles.active}`}>Главная</span>:<button className={styles.textButton} disabled={busy} onClick={()=>void makePrimary(item)}>Сделать главной</button>}</div>)}{media.length===0&&<p className={styles.hint}>Загруженных фотографий пока нет.</p>}</div></CollapsibleSection></>}
    </div>{id&&<aside className={styles.readiness}><h2>{status==="ARCHIVED"?"Товар в архиве":"Готовность товара"}</h2>{status!=="ARCHIVED"&&readiness.map(item=><div className={item.ready?styles.ready:styles.notReady} key={item.label}><span>{item.ready?"✓":"○"}</span>{item.label}</div>)}{status!=="ARCHIVED"&&<div className={hasAvailableStock?styles.ready:styles.notReady}><span>{hasAvailableStock?"✓":"○"}</span>{hasAvailableStock===null?"Проверяем склад":hasAvailableStock?"Есть доступный остаток":"На складе пока пусто"}</div>}<p>{status==="ARCHIVED"?"Товар не показывается на витрине и убран из рабочего списка.":ready?hasAvailableStock===false?"Карточка готова. При публикации товар будет отмечен как отсутствующий.":"Карточка готова к публикации.":"Заполните недостающие пункты."}</p>{status==="ARCHIVED"?<><button className={styles.primary} disabled={busy} onClick={()=>void transition("restore")}>Восстановить</button><button className={styles.danger} disabled={busy} onClick={()=>void remove()}>Удалить навсегда</button></>:<>{status==="ACTIVE"?<button className={styles.danger} disabled={busy} onClick={()=>void transition("archive")}>Убрать в архив</button>:<><button className={styles.primary} disabled={busy} onClick={()=>void transition("publish")}>Опубликовать товар</button><a className={styles.secondary} href="/admin/inventory">Открыть склад</a><button className={styles.secondary} disabled={busy} onClick={()=>void transition("archive")}>Убрать в архив</button></>}</>}</aside>}</div>
  </>;
}

function Field({label,full=false,children}:{label:string;full?:boolean;children:React.ReactNode}){return <label className={`${styles.field} ${full?styles.full:""}`}><span>{label}</span>{children}</label>}

function CollapsibleSection({title,children}:{title:string;children:React.ReactNode}){const [open,setOpen]=useState(true);return <section className={`${styles.panel} ${styles.collapsiblePanel}`}><button type="button" className={styles.collapsibleTrigger} aria-expanded={open} onClick={()=>setOpen(current=>!current)}><h2>{title}</h2><span aria-hidden="true">⌄</span></button>{open&&<div className={styles.collapsibleContent}>{children}</div>}</section>}

function toLocalDateTime(value:string|Date){const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}

function formatFileSize(bytes:number){return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} МБ`:`${Math.ceil(bytes/1024)} КБ`}

function uploadFile(url:string,file:File,onProgress:(percent:number)=>void){return new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();request.open("PUT",url);request.setRequestHeader("Content-Type",file.type);request.upload.addEventListener("progress",event=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))});request.addEventListener("load",()=>request.status>=200&&request.status<300?resolve():reject(new Error("Не удалось загрузить фотографию")));request.addEventListener("error",()=>reject(new Error("Соединение прервалось во время загрузки")));request.addEventListener("abort",()=>reject(new Error("Загрузка фотографии отменена")));request.send(file)})}
