ALTER DEFAULT PRIVILEGES FOR ROLE amra_migrator IN SCHEMA amra_shop
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO amra_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE amra_migrator IN SCHEMA amra_shop
    GRANT USAGE, SELECT ON SEQUENCES TO amra_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE amra_migrator IN SCHEMA amra_shop
    GRANT EXECUTE ON FUNCTIONS TO amra_runtime;
