"use client";

import { useEffect, useState } from "react";
import { api, type StorefrontBanner, type StorefrontBannerList } from "../api";
import shared from "../admin.module.css";
import styles from "./banners.module.css";

type Upload = { objectKey:string; uploadUrl:string };
type Form = { internalName:string; eyebrow:string; title:string; description:string; status:StorefrontBanner["status"]; displayOrder:number; startsAt:string; endsAt:string };
const emptyForm:Form={internalName:"",eyebrow:"На каждый день",title:"",description:"",status:"DRAFT",displayOrder:0,startsAt:"",endsAt:""};

export default function BannersPage(){
  const [items,setItems]=useState<StorefrontBanner[]>([]),[selected,setSelected]=useState<StorefrontBanner|null>(null),[form,setForm]=useState<Form>(emptyForm),[desktop,setDesktop]=useState<File|null>(null),[mobile,setMobile]=useState<File|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState<number|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const previewDesktop=useObjectUrl(desktop),previewMobile=useObjectUrl(mobile);
  const open=(banner:StorefrontBanner)=>{setSelected(banner);setForm({internalName:banner.internalName,eyebrow:banner.eyebrow,title:banner.title,description:banner.description,status:banner.status,displayOrder:banner.displayOrder,startsAt:toLocal(banner.startsAt),endsAt:toLocal(banner.endsAt)});setDesktop(null);setMobile(null);setMessage("");setError("")};
  const load=async()=>{const {data}=await api<StorefrontBannerList>("/admin/storefront/banners");setItems(data.items);return data.items};
  useEffect(()=>{void load().then(loaded=>{if(loaded[0])open(loaded[0])}).catch(reason=>setError((reason as Error).message))},[]);
  const create=()=>{setSelected(null);setForm({...emptyForm,displayOrder:items.length});setDesktop(null);setMobile(null);setMessage("");setError("")};
  const update=<K extends keyof Form>(key:K,value:Form[K])=>setForm(current=>({...current,[key]:value}));
  const save=async()=>{if(!form.internalName.trim()||!form.title.trim()||!form.description.trim()){setError("Заполните название для сотрудников, заголовок и описание.");return}setBusy(true);setError("");setMessage("");setProgress(null);try{
    let banner=selected,etag=selected?`"v${selected.version}"`:null;
    const draftPayload=payload(form,{desktopObjectKey:selected?.desktopObjectKey??null,mobileObjectKey:selected?.mobileObjectKey??null,status:(desktop||!selected?.desktopObjectKey)&&form.status==="PUBLISHED"?"DRAFT":form.status});
    if(!banner){const created=await api<StorefrontBanner>("/admin/storefront/banners",{method:"POST",body:JSON.stringify(draftPayload)});banner=created.data;etag=created.etag}
    let desktopKey=banner.desktopObjectKey??null,mobileKey=banner.mobileObjectKey??null;
    const uploads=[desktop?{file:desktop,kind:"desktop" as const}:null,mobile?{file:mobile,kind:"mobile" as const}:null].filter(Boolean) as Array<{file:File;kind:"desktop"|"mobile"}>;
    for(let index=0;index<uploads.length;index++){const item=uploads[index];setProgress(Math.round(index/uploads.length*100));const reservation=await api<Upload>(`/admin/storefront/banners/${banner.id}/uploads`,{method:"POST",body:JSON.stringify({fileName:item.file.name,contentType:item.file.type,size:item.file.size})});await uploadFile(reservation.data.uploadUrl,item.file,value=>setProgress(Math.round((index+value/100)/uploads.length*100)));if(item.kind==="desktop")desktopKey=reservation.data.objectKey;else mobileKey=reservation.data.objectKey}
    const finalPayload=payload(form,{desktopObjectKey:desktopKey,mobileObjectKey:mobileKey,status:form.status});
    const saved=await api<StorefrontBanner>(`/admin/storefront/banners/${banner.id}`,{method:"PUT",headers:etag?{"If-Match":etag}:{},body:JSON.stringify(finalPayload)});
    setSelected(saved.data);setDesktop(null);setMobile(null);setProgress(100);setMessage(form.status==="PUBLISHED"?"Баннер опубликован на витрине":"Баннер сохранён");await load();
  }catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  return <>
    <div className={shared.heading}><div><p className={shared.eyebrow}>Витрина</p><h1>Баннеры</h1><p>Управляйте первым экраном магазина без изменений во frontend-коде.</p></div><button className={shared.primary} onClick={create}>Новый баннер</button></div>
    {error&&<div className={shared.error}>{error}</div>}{message&&<div className={shared.message}>{message}</div>}
    <div className={styles.layout}><section className={styles.list} aria-label="Баннеры витрины">{items.map(item=><button className={`${styles.bannerCard} ${selected?.id===item.id?styles.selected:""}`} onClick={()=>open(item)} key={item.id}>{item.desktopImageUrl?<img src={item.desktopImageUrl} alt=""/>:<span className={styles.placeholder}>Нет фото</span>}<span className={styles.cardCopy}><span className={`${shared.badge} ${item.status==="PUBLISHED"?shared.active:item.status==="DRAFT"?shared.draft:""}`}>{statusLabel(item.status)}</span><strong>{item.internalName}</strong><small>{item.title}</small></span><b>{String(item.displayOrder+1).padStart(2,"0")}</b></button>)}{items.length===0&&<div className={styles.empty}>Баннеров пока нет. Создайте первый и загрузите фотографию.</div>}</section>
      <section className={styles.editor}><div className={styles.editorHead}><div><span>{selected?"Редактирование":"Новый баннер"}</span><h2>{form.internalName||"Без названия"}</h2></div>{selected?.desktopImageUrl&&<a href="/" target="_blank">Открыть витрину ↗</a>}</div>
        <div className={styles.preview}><picture>{(previewMobile||selected?.mobileImageUrl)&&<source media="(max-width: 600px)" srcSet={previewMobile||selected?.mobileImageUrl||""}/>}<img src={previewDesktop||selected?.desktopImageUrl||"/amra-hero-hoodies-v2.png"} alt="Предпросмотр баннера"/></picture><div><span>{form.eyebrow}</span><h3>{form.title||"Заголовок баннера"}</h3><p>{form.description||"Короткое описание предложения"}</p></div></div>
        <div className={styles.formGrid}><Field label="Название для сотрудников"><input value={form.internalName} onChange={e=>update("internalName",e.target.value)} placeholder="Например, Худи — август"/></Field><Field label="Надзаголовок"><input value={form.eyebrow} onChange={e=>update("eyebrow",e.target.value)}/></Field><Field label="Заголовок"><input value={form.title} onChange={e=>update("title",e.target.value)} placeholder="Худи и свитшоты"/></Field><Field label="Описание" full><textarea value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Одно короткое предложение"/></Field><Field label="Порядок"><input type="number" min="0" value={form.displayOrder} onChange={e=>update("displayOrder",Number(e.target.value))}/></Field><Field label="Статус"><select value={form.status} onChange={e=>update("status",e.target.value as Form["status"])}><option value="DRAFT">Черновик</option><option value="PUBLISHED">Опубликован</option><option value="ARCHIVED">Архив</option></select></Field><Field label="Начало показа"><input type="datetime-local" value={form.startsAt} onChange={e=>update("startsAt",e.target.value)}/></Field><Field label="Окончание показа"><input type="datetime-local" value={form.endsAt} onChange={e=>update("endsAt",e.target.value)}/></Field></div>
        <div className={styles.uploadGrid}><ImagePicker title="Desktop-фотография" hint="Рекомендуемый формат 1920 × 900" file={desktop} current={selected?.desktopImageUrl} onChange={setDesktop}/><ImagePicker title="Mobile-фотография" hint="Необязательно · рекомендуемый формат 900 × 1200" file={mobile} current={selected?.mobileImageUrl} onChange={setMobile}/></div>
        {progress!==null&&<div className={styles.progress}><span>Загрузка фотографий <b>{progress}%</b></span><progress max="100" value={progress}/></div>}
        <div className={styles.actions}><button className={shared.secondary} onClick={()=>selected?open(selected):create()} disabled={busy}>Сбросить</button><button className={shared.primary} onClick={()=>void save()} disabled={busy}>{busy?"Сохраняем…":form.status==="PUBLISHED"?"Сохранить и опубликовать":"Сохранить"}</button></div>
      </section></div>
  </>;
}

function Field({label,full=false,children}:{label:string;full?:boolean;children:React.ReactNode}){return <label className={`${styles.field} ${full?styles.full:""}`}><span>{label}</span>{children}</label>}
function ImagePicker({title,hint,file,current,onChange}:{title:string;hint:string;file:File|null;current?:string|null;onChange:(file:File|null)=>void}){const preview=useObjectUrl(file);return <label className={styles.imagePicker}>{preview||current?<img src={preview||current||""} alt=""/>:<span className={styles.addIcon}>＋</span>}<strong>{title}</strong><small>{file?.name||hint}</small><b>{file?"Заменить файл":"Выбрать фотографию"}</b><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>onChange(e.target.files?.[0]??null)}/></label>}
function useObjectUrl(file:File|null){const [url,setUrl]=useState("");useEffect(()=>{if(!file){setUrl("");return}const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next)},[file]);return url}
function payload(form:Form,media:{desktopObjectKey:string|null;mobileObjectKey:string|null;status:StorefrontBanner["status"]}){return {...form,buttonLabel:"Без кнопки",targetType:"URL",targetValue:"/",desktopObjectKey:media.desktopObjectKey,mobileObjectKey:media.mobileObjectKey,status:media.status,startsAt:form.startsAt?new Date(form.startsAt).toISOString():null,endsAt:form.endsAt?new Date(form.endsAt).toISOString():null}}
function toLocal(value?:string|Date|null){if(!value)return"";const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}
function statusLabel(status:StorefrontBanner["status"]){return status==="PUBLISHED"?"Опубликован":status==="DRAFT"?"Черновик":"Архив"}
function uploadFile(url:string,file:File,onProgress:(value:number)=>void){return new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();request.open("PUT",url);request.setRequestHeader("Content-Type",file.type);request.upload.onprogress=event=>event.lengthComputable&&onProgress(Math.round(event.loaded/event.total*100));request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error("Не удалось загрузить фотографию"));request.onerror=()=>reject(new Error("Соединение прервалось во время загрузки"));request.send(file)})}
